name: dirasati
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  animated_size_and_fade: ^5.1.1
  build_runner: ^2.4.7
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.3.0
  dio: ^5.8.0+1
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_gen: ^5.11.0
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_pdfview: ^1.4.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_staggered_animations: ^1.1.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  http: ^1.3.0
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  intl: ^0.19.0 
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  path: ^1.9.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^29.1.38
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.3 # ✅ Needed for localization with intl: 0.19.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: "Inter"
      fonts:
        - asset: "assets/fonts/Inter-VariableFont_opsz,wght.ttf"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#073B4C"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false
